#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libsafec
Version  : 03032018
Release  : 1
URL      : https://github.com/rurban/safeclib/releases/download/v03032018/libsafec-03032018.0-g570fa5.tar.xz
Source0  : https://github.com/rurban/safeclib/releases/download/v03032018/libsafec-03032018.0-g570fa5.tar.xz
Summary  : A safe coding library for C, ref ISO TR24731, C11 Annex K
Group    : Development/Tools
License  : MIT
Requires: libsafec-bin
Requires: libsafec-lib
Requires: libsafec-license
Requires: libsafec-man
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : doxygen
BuildRequires : gettext-bin
BuildRequires : graphviz
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : pkg-config-dev
BuildRequires : valgrind
Patch1: build.patch
Patch2: pkgconfig_include.patch

%description
=======================
:toc:
Copying
-------
This project's licensing restrictions are documented in the file 'COPYING'
under the root directory of this release. Basically it's MIT licensed.

%package bin
Summary: bin components for the libsafec package.
Group: Binaries
Requires: libsafec-license
Requires: libsafec-man

%description bin
bin components for the libsafec package.


%package dev
Summary: dev components for the libsafec package.
Group: Development
Requires: libsafec-lib
Requires: libsafec-bin
Provides: libsafec-devel

%description dev
dev components for the libsafec package.


%package lib
Summary: lib components for the libsafec package.
Group: Libraries
Requires: libsafec-license

%description lib
lib components for the libsafec package.


%package license
Summary: license components for the libsafec package.
Group: Default

%description license
license components for the libsafec package.


%package man
Summary: man components for the libsafec package.
Group: Default

%description man
man components for the libsafec package.


%prep
%setup -q -n libsafec-03032018.0-g570fa5
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534953602
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1534953602
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libsafec
cp COPYING %{buildroot}/usr/share/doc/libsafec/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/check_for_unsafe_apis

%files dev
%defattr(-,root,root,-)
/usr/include/libsafec/safe_compile.h
/usr/include/libsafec/safe_config.h
/usr/include/libsafec/safe_lib.h
/usr/include/libsafec/safe_lib_errno.h
/usr/include/libsafec/safe_mem_lib.h
/usr/include/libsafec/safe_str_lib.h
/usr/include/libsafec/safe_types.h
/usr/lib64/libsafec-3.3.so
/usr/lib64/pkgconfig/safec-3.3.pc
/usr/share/man/man3/EOK.3
/usr/share/man/man3/ESEMPTY.3
/usr/share/man/man3/ESLAST.3
/usr/share/man/man3/ESLEMAX.3
/usr/share/man/man3/ESLEMIN.3
/usr/share/man/man3/ESLEWRNG.3
/usr/share/man/man3/ESNODIFF.3
/usr/share/man/man3/ESNOSPC.3
/usr/share/man/man3/ESNOTFND.3
/usr/share/man/man3/ESNULLP.3
/usr/share/man/man3/ESOVRLP.3
/usr/share/man/man3/ESUNTERM.3
/usr/share/man/man3/ESZEROL.3
/usr/share/man/man3/L_tmpnam_s.3
/usr/share/man/man3/RSIZE_MAX.3
/usr/share/man/man3/RSIZE_MAX_MEM.3
/usr/share/man/man3/RSIZE_MAX_MEM16.3
/usr/share/man/man3/RSIZE_MAX_MEM32.3
/usr/share/man/man3/RSIZE_MAX_STR.3
/usr/share/man/man3/RSIZE_MAX_WMEM.3
/usr/share/man/man3/RSIZE_MAX_WSTR.3
/usr/share/man/man3/RSIZE_MIN_STR.3
/usr/share/man/man3/SAFECLIB_STR_NULL_SLACK.3
/usr/share/man/man3/SAFE_STR_MIN_LOWERCASE.3
/usr/share/man/man3/SAFE_STR_MIN_NUMBERS.3
/usr/share/man/man3/SAFE_STR_MIN_SPECIALS.3
/usr/share/man/man3/SAFE_STR_MIN_UPPERCASE.3
/usr/share/man/man3/SAFE_STR_PASSWORD_MAX_LENGTH.3
/usr/share/man/man3/SAFE_STR_PASSWORD_MIN_LENGTH.3
/usr/share/man/man3/STRTOK_DELIM_MAX_LEN.3
/usr/share/man/man3/TMP_MAX_S.3
/usr/share/man/man3/abort_handler_s.3
/usr/share/man/man3/abort_handler_s.c.3
/usr/share/man/man3/asctime_s.3
/usr/share/man/man3/asctime_s.c.3
/usr/share/man/man3/bsearch_s.3
/usr/share/man/man3/bsearch_s.c.3
/usr/share/man/man3/constraint_handler_t.3
/usr/share/man/man3/ctime_s.3
/usr/share/man/man3/ctime_s.c.3
/usr/share/man/man3/fopen_s.3
/usr/share/man/man3/fopen_s.c.3
/usr/share/man/man3/fprintf_s.3
/usr/share/man/man3/fprintf_s.c.3
/usr/share/man/man3/freopen_s.3
/usr/share/man/man3/freopen_s.c.3
/usr/share/man/man3/fscanf_s.3
/usr/share/man/man3/fscanf_s.c.3
/usr/share/man/man3/fwprintf_s.3
/usr/share/man/man3/fwprintf_s.c.3
/usr/share/man/man3/fwscanf_s.3
/usr/share/man/man3/fwscanf_s.c.3
/usr/share/man/man3/getenv_s.3
/usr/share/man/man3/getenv_s.c.3
/usr/share/man/man3/gets_s.3
/usr/share/man/man3/gets_s.c.3
/usr/share/man/man3/gmtime_s.3
/usr/share/man/man3/gmtime_s.c.3
/usr/share/man/man3/ignore_handler_s.3
/usr/share/man/man3/ignore_handler_s.c.3
/usr/share/man/man3/invoke_safe_mem_constraint_handler.3
/usr/share/man/man3/invoke_safe_str_constraint_handler.3
/usr/share/man/man3/localtime_s.3
/usr/share/man/man3/localtime_s.c.3
/usr/share/man/man3/mbsrtowcs_s.3
/usr/share/man/man3/mbsrtowcs_s.c.3
/usr/share/man/man3/mbstowcs_s.3
/usr/share/man/man3/mbstowcs_s.c.3
/usr/share/man/man3/mem_handler.3
/usr/share/man/man3/mem_prim_move.3
/usr/share/man/man3/mem_prim_move16.3
/usr/share/man/man3/mem_prim_move32.3
/usr/share/man/man3/mem_prim_move8.3
/usr/share/man/man3/mem_prim_set.3
/usr/share/man/man3/mem_prim_set16.3
/usr/share/man/man3/mem_prim_set32.3
/usr/share/man/man3/mem_primitives_lib.c.3
/usr/share/man/man3/mem_primitives_lib.h.3
/usr/share/man/man3/memccpy_s.3
/usr/share/man/man3/memccpy_s.c.3
/usr/share/man/man3/memchr_s.3
/usr/share/man/man3/memchr_s.c.3
/usr/share/man/man3/memcmp16_s.3
/usr/share/man/man3/memcmp16_s.c.3
/usr/share/man/man3/memcmp32_s.3
/usr/share/man/man3/memcmp32_s.c.3
/usr/share/man/man3/memcmp_s.3
/usr/share/man/man3/memcmp_s.c.3
/usr/share/man/man3/memcpy16_s.3
/usr/share/man/man3/memcpy16_s.c.3
/usr/share/man/man3/memcpy32_s.3
/usr/share/man/man3/memcpy32_s.c.3
/usr/share/man/man3/memcpy_s.3
/usr/share/man/man3/memcpy_s.c.3
/usr/share/man/man3/memmove16_s.3
/usr/share/man/man3/memmove16_s.c.3
/usr/share/man/man3/memmove32_s.3
/usr/share/man/man3/memmove32_s.c.3
/usr/share/man/man3/memmove_s.3
/usr/share/man/man3/memmove_s.c.3
/usr/share/man/man3/memrchr_s.3
/usr/share/man/man3/memrchr_s.c.3
/usr/share/man/man3/memset16_s.3
/usr/share/man/man3/memset16_s.c.3
/usr/share/man/man3/memset32_s.3
/usr/share/man/man3/memset32_s.c.3
/usr/share/man/man3/memset_s.3
/usr/share/man/man3/memset_s.c.3
/usr/share/man/man3/memzero16_s.3
/usr/share/man/man3/memzero16_s.c.3
/usr/share/man/man3/memzero32_s.3
/usr/share/man/man3/memzero32_s.c.3
/usr/share/man/man3/memzero_s.3
/usr/share/man/man3/memzero_s.c.3
/usr/share/man/man3/printf_s.3
/usr/share/man/man3/printf_s.c.3
/usr/share/man/man3/qsort_s.3
/usr/share/man/man3/qsort_s.c.3
/usr/share/man/man3/rsize_t.3
/usr/share/man/man3/safe_compile.h.3
/usr/share/man/man3/safe_config.h.3
/usr/share/man/man3/safe_lib.h.3
/usr/share/man/man3/safe_lib_errno.h.3
/usr/share/man/man3/safe_mem_constraint.c.3
/usr/share/man/man3/safe_mem_constraint.h.3
/usr/share/man/man3/safe_mem_lib.h.3
/usr/share/man/man3/safe_str_constraint.c.3
/usr/share/man/man3/safe_str_constraint.h.3
/usr/share/man/man3/safe_str_lib.h.3
/usr/share/man/man3/safe_types.h.3
/usr/share/man/man3/scanf_s.3
/usr/share/man/man3/scanf_s.c.3
/usr/share/man/man3/set_mem_constraint_handler_s.3
/usr/share/man/man3/set_str_constraint_handler_s.3
/usr/share/man/man3/snprintf_s.3
/usr/share/man/man3/snprintf_s.c.3
/usr/share/man/man3/snwprintf_s.3
/usr/share/man/man3/snwprintf_s.c.3
/usr/share/man/man3/sprintf_s.3
/usr/share/man/man3/sprintf_s.c.3
/usr/share/man/man3/sscanf_s.3
/usr/share/man/man3/sscanf_s.c.3
/usr/share/man/man3/str_handler.3
/usr/share/man/man3/strcasecmp_s.3
/usr/share/man/man3/strcasecmp_s.c.3
/usr/share/man/man3/strcasestr_s.3
/usr/share/man/man3/strcasestr_s.c.3
/usr/share/man/man3/strcat_s.3
/usr/share/man/man3/strcat_s.c.3
/usr/share/man/man3/strchr_s.3
/usr/share/man/man3/strchr_s.c.3
/usr/share/man/man3/strcmp_s.3
/usr/share/man/man3/strcmp_s.c.3
/usr/share/man/man3/strcmpfld_s.3
/usr/share/man/man3/strcmpfld_s.c.3
/usr/share/man/man3/strcoll_s.3
/usr/share/man/man3/strcoll_s.c.3
/usr/share/man/man3/strcpy_s.3
/usr/share/man/man3/strcpy_s.c.3
/usr/share/man/man3/strcpyfld_s.3
/usr/share/man/man3/strcpyfld_s.c.3
/usr/share/man/man3/strcpyfldin_s.3
/usr/share/man/man3/strcpyfldin_s.c.3
/usr/share/man/man3/strcpyfldout_s.3
/usr/share/man/man3/strcpyfldout_s.c.3
/usr/share/man/man3/strcspn_s.3
/usr/share/man/man3/strcspn_s.c.3
/usr/share/man/man3/strerror_s.3
/usr/share/man/man3/strerror_s.c.3
/usr/share/man/man3/strerror_s.h.3
/usr/share/man/man3/strerrorlen_s.3
/usr/share/man/man3/strfirstchar_s.3
/usr/share/man/man3/strfirstchar_s.c.3
/usr/share/man/man3/strfirstdiff_s.3
/usr/share/man/man3/strfirstdiff_s.c.3
/usr/share/man/man3/strfirstsame_s.3
/usr/share/man/man3/strfirstsame_s.c.3
/usr/share/man/man3/strisalphanumeric_s.3
/usr/share/man/man3/strisalphanumeric_s.c.3
/usr/share/man/man3/strisascii_s.3
/usr/share/man/man3/strisascii_s.c.3
/usr/share/man/man3/strisdigit_s.3
/usr/share/man/man3/strisdigit_s.c.3
/usr/share/man/man3/strishex_s.3
/usr/share/man/man3/strishex_s.c.3
/usr/share/man/man3/strislowercase_s.3
/usr/share/man/man3/strislowercase_s.c.3
/usr/share/man/man3/strismixedcase_s.3
/usr/share/man/man3/strismixedcase_s.c.3
/usr/share/man/man3/strispassword_s.3
/usr/share/man/man3/strispassword_s.c.3
/usr/share/man/man3/strisuppercase_s.3
/usr/share/man/man3/strisuppercase_s.c.3
/usr/share/man/man3/strlastchar_s.3
/usr/share/man/man3/strlastchar_s.c.3
/usr/share/man/man3/strlastdiff_s.3
/usr/share/man/man3/strlastdiff_s.c.3
/usr/share/man/man3/strlastsame_s.3
/usr/share/man/man3/strlastsame_s.c.3
/usr/share/man/man3/strljustify_s.3
/usr/share/man/man3/strljustify_s.c.3
/usr/share/man/man3/strlwr_s.3
/usr/share/man/man3/strnatcasecmp_s.3
/usr/share/man/man3/strnatcmp_s.3
/usr/share/man/man3/strnatcmp_s.c.3
/usr/share/man/man3/strncat_s.3
/usr/share/man/man3/strncat_s.c.3
/usr/share/man/man3/strncpy_s.3
/usr/share/man/man3/strncpy_s.c.3
/usr/share/man/man3/strnlen_s.3
/usr/share/man/man3/strnlen_s.c.3
/usr/share/man/man3/strnset_s.3
/usr/share/man/man3/strnset_s.c.3
/usr/share/man/man3/strnterminate_s.3
/usr/share/man/man3/strnterminate_s.c.3
/usr/share/man/man3/strpbrk_s.3
/usr/share/man/man3/strpbrk_s.c.3
/usr/share/man/man3/strprefix_s.3
/usr/share/man/man3/strprefix_s.c.3
/usr/share/man/man3/strrchr_s.3
/usr/share/man/man3/strrchr_s.c.3
/usr/share/man/man3/strremovews_s.3
/usr/share/man/man3/strremovews_s.c.3
/usr/share/man/man3/strset_s.3
/usr/share/man/man3/strset_s.c.3
/usr/share/man/man3/strspn_s.3
/usr/share/man/man3/strspn_s.c.3
/usr/share/man/man3/strstr_s.3
/usr/share/man/man3/strstr_s.c.3
/usr/share/man/man3/strtok_s.3
/usr/share/man/man3/strtok_s.c.3
/usr/share/man/man3/strtolowercase_s.3
/usr/share/man/man3/strtolowercase_s.c.3
/usr/share/man/man3/strtouppercase_s.3
/usr/share/man/man3/strtouppercase_s.c.3
/usr/share/man/man3/strupr_s.3
/usr/share/man/man3/strzero_s.3
/usr/share/man/man3/strzero_s.c.3
/usr/share/man/man3/swprintf_s.3
/usr/share/man/man3/swprintf_s.c.3
/usr/share/man/man3/swscanf_s.3
/usr/share/man/man3/swscanf_s.c.3
/usr/share/man/man3/timingsafe_bcmp.3
/usr/share/man/man3/timingsafe_bcmp.c.3
/usr/share/man/man3/timingsafe_memcmp.3
/usr/share/man/man3/timingsafe_memcmp.c.3
/usr/share/man/man3/tmpfile_s.3
/usr/share/man/man3/tmpfile_s.c.3
/usr/share/man/man3/tmpnam_s.3
/usr/share/man/man3/tmpnam_s.c.3
/usr/share/man/man3/towctrans.c.3
/usr/share/man/man3/towfc_s.3
/usr/share/man/man3/towfc_s.c.3
/usr/share/man/man3/towlower.3
/usr/share/man/man3/towupper.3
/usr/share/man/man3/unw16ifcan.h.3
/usr/share/man/man3/unw16ifcmb.h.3
/usr/share/man/man3/unw16ifcmp.h.3
/usr/share/man/man3/unw16ifcpt.h.3
/usr/share/man/man3/unw16ifexc.h.3
/usr/share/man/man3/unwifcan.h.3
/usr/share/man/man3/unwifcmb.h.3
/usr/share/man/man3/unwifcmp.h.3
/usr/share/man/man3/unwifcpt.h.3
/usr/share/man/man3/unwifexc.h.3
/usr/share/man/man3/vfprintf_s.3
/usr/share/man/man3/vfprintf_s.c.3
/usr/share/man/man3/vfscanf_s.3
/usr/share/man/man3/vfscanf_s.c.3
/usr/share/man/man3/vfwprintf_s.3
/usr/share/man/man3/vfwprintf_s.c.3
/usr/share/man/man3/vfwscanf_s.3
/usr/share/man/man3/vfwscanf_s.c.3
/usr/share/man/man3/vprintf_s.3
/usr/share/man/man3/vprintf_s.c.3
/usr/share/man/man3/vscanf_s.3
/usr/share/man/man3/vscanf_s.c.3
/usr/share/man/man3/vsnprintf_s.3
/usr/share/man/man3/vsnprintf_s.c.3
/usr/share/man/man3/vsnwprintf_s.3
/usr/share/man/man3/vsnwprintf_s.c.3
/usr/share/man/man3/vsprintf_s.3
/usr/share/man/man3/vsprintf_s.c.3
/usr/share/man/man3/vsscanf_s.3
/usr/share/man/man3/vsscanf_s.c.3
/usr/share/man/man3/vswprintf_s.3
/usr/share/man/man3/vswprintf_s.c.3
/usr/share/man/man3/vswscanf_s.3
/usr/share/man/man3/vswscanf_s.c.3
/usr/share/man/man3/vwprintf_s.3
/usr/share/man/man3/vwprintf_s.c.3
/usr/share/man/man3/vwscanf_s.3
/usr/share/man/man3/vwscanf_s.c.3
/usr/share/man/man3/wcrtomb_s.3
/usr/share/man/man3/wcrtomb_s.c.3
/usr/share/man/man3/wcscat_s.3
/usr/share/man/man3/wcscat_s.c.3
/usr/share/man/man3/wcscmp_s.3
/usr/share/man/man3/wcscmp_s.c.3
/usr/share/man/man3/wcscoll_s.3
/usr/share/man/man3/wcscoll_s.c.3
/usr/share/man/man3/wcscpy_s.3
/usr/share/man/man3/wcscpy_s.c.3
/usr/share/man/man3/wcsfc_s.3
/usr/share/man/man3/wcsfc_s.c.3
/usr/share/man/man3/wcsicmp_s.3
/usr/share/man/man3/wcsicmp_s.c.3
/usr/share/man/man3/wcslwr_s.3
/usr/share/man/man3/wcslwr_s.c.3
/usr/share/man/man3/wcsnatcmp_s.3
/usr/share/man/man3/wcsnatcmp_s.c.3
/usr/share/man/man3/wcsnaticmp_s.3
/usr/share/man/man3/wcsncat_s.3
/usr/share/man/man3/wcsncat_s.c.3
/usr/share/man/man3/wcsncmp_s.3
/usr/share/man/man3/wcsncmp_s.c.3
/usr/share/man/man3/wcsncpy_s.3
/usr/share/man/man3/wcsncpy_s.c.3
/usr/share/man/man3/wcsnlen_s.3
/usr/share/man/man3/wcsnlen_s.c.3
/usr/share/man/man3/wcsnorm_compose_s.3
/usr/share/man/man3/wcsnorm_decompose_s.3
/usr/share/man/man3/wcsnorm_reorder_s.3
/usr/share/man/man3/wcsnorm_s.3
/usr/share/man/man3/wcsnorm_s.c.3
/usr/share/man/man3/wcsnset_s.3
/usr/share/man/man3/wcsnset_s.c.3
/usr/share/man/man3/wcsrtombs_s.3
/usr/share/man/man3/wcsrtombs_s.c.3
/usr/share/man/man3/wcsset_s.3
/usr/share/man/man3/wcsset_s.c.3
/usr/share/man/man3/wcsstr.3
/usr/share/man/man3/wcsstr.c.3
/usr/share/man/man3/wcsstr_s.3
/usr/share/man/man3/wcsstr_s.c.3
/usr/share/man/man3/wcstok_s.3
/usr/share/man/man3/wcstok_s.c.3
/usr/share/man/man3/wcstombs_s.3
/usr/share/man/man3/wcstombs_s.c.3
/usr/share/man/man3/wcsupr_s.3
/usr/share/man/man3/wcsupr_s.c.3
/usr/share/man/man3/wctomb_s.3
/usr/share/man/man3/wctomb_s.c.3
/usr/share/man/man3/wmemcmp_s.3
/usr/share/man/man3/wmemcmp_s.c.3
/usr/share/man/man3/wmemcpy_s.3
/usr/share/man/man3/wmemcpy_s.c.3
/usr/share/man/man3/wmemmove_s.3
/usr/share/man/man3/wmemmove_s.c.3
/usr/share/man/man3/wprintf_s.3
/usr/share/man/man3/wprintf_s.c.3
/usr/share/man/man3/wscanf_s.3
/usr/share/man/man3/wscanf_s.c.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsafec-3.3.so.3
/usr/lib64/libsafec-3.3.so.3.0.3

%files license
%defattr(-,root,root,-)
/usr/share/doc/libsafec/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/check_for_unsafe_apis.1
