#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libsafec
Version  : 03032018
Release  : 2
URL      : https://github.com/rurban/safeclib/releases/download/v03032018/libsafec-03032018.0-g570fa5.tar.xz
Source0  : https://github.com/rurban/safeclib/releases/download/v03032018/libsafec-03032018.0-g570fa5.tar.xz
Summary  : A safe coding library for C, ref ISO TR24731, C11 Annex K
Group    : Development/Tools
License  : MIT
Requires: libsafec-bin
Requires: libsafec-lib
Requires: libsafec-license
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : doxygen
BuildRequires : gettext-bin
BuildRequires : graphviz
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : pkg-config-dev
BuildRequires : valgrind
Patch1: build.patch
Patch2: pkgconfig_include.patch

%description
=======================
:toc:
Copying
-------
This project's licensing restrictions are documented in the file 'COPYING'
under the root directory of this release. Basically it's MIT licensed.

%package bin
Summary: bin components for the libsafec package.
Group: Binaries
Requires: libsafec-license

%description bin
bin components for the libsafec package.


%package dev
Summary: dev components for the libsafec package.
Group: Development
Requires: libsafec-lib
Requires: libsafec-bin
Provides: libsafec-devel

%description dev
dev components for the libsafec package.


%package lib
Summary: lib components for the libsafec package.
Group: Libraries
Requires: libsafec-license

%description lib
lib components for the libsafec package.


%package license
Summary: license components for the libsafec package.
Group: Default

%description license
license components for the libsafec package.


%prep
%setup -q -n libsafec-03032018.0-g570fa5
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536122981
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1536122981
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libsafec
cp COPYING %{buildroot}/usr/share/doc/libsafec/COPYING
%make_install
## install_append content
rm -rf %{buildroot}/usr/share/man
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/check_for_unsafe_apis

%files dev
%defattr(-,root,root,-)
/usr/include/libsafec/safe_compile.h
/usr/include/libsafec/safe_config.h
/usr/include/libsafec/safe_lib.h
/usr/include/libsafec/safe_lib_errno.h
/usr/include/libsafec/safe_mem_lib.h
/usr/include/libsafec/safe_str_lib.h
/usr/include/libsafec/safe_types.h
/usr/lib64/libsafec-3.3.so
/usr/lib64/pkgconfig/safec-3.3.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsafec-3.3.so.3
/usr/lib64/libsafec-3.3.so.3.0.3

%files license
%defattr(-,root,root,-)
/usr/share/doc/libsafec/COPYING
